### ISSUE TITLE
[transaction] Polling aborted due to IllegalStateException

### ISSUE THREAD

**Issue by mhilbush** [openhab/org.openhab.binding.zwave#115]
I started seeing these exceptions in the log.  I'm running PR build 106.  Not sure if this is related to the queuing issue you've been working on.  If so, you can close this.

```
2016-09-19 20:39:35.608 [WARN ] [ding.zwave.handler.ZWaveThingHandler] - NODE 8: Polling aborted due to exception
java.lang.IllegalStateException: Timer already cancelled.
        at java.util.Timer.sched(Timer.java:397)[:1.8.0_91]
        at java.util.Timer.schedule(Timer.java:208)[:1.8.0_91]
        at org.openhab.binding.zwave.internal.protocol.ZWaveTransactionManager.startTransactionTimer(ZWaveTransactionManager.java:445)[187:org.openhab.binding.zwave:2.0.0.201609181624]
        at org.openhab.binding.zwave.internal.protocol.ZWaveTransactionManager.queueTransactionForSend(ZWaveTransactionManager.java:171)[187:org.openhab.binding.zwave:2.0.0.201609181624]
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.enqueue(ZWaveController.java:493)[187:org.openhab.binding.zwave:2.0.0.201609181624]
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.sendData(ZWaveController.java:1043)[187:org.openhab.binding.zwave:2.0.0.201609181624]
        at org.openhab.binding.zwave.handler.ZWaveControllerHandler.sendData(ZWaveControllerHandler.java:634)[187:org.openhab.binding.zwave:2.0.0.201609181624]
        at org.openhab.binding.zwave.handler.ZWaveThingHandler$1.run(ZWaveThingHandler.java:393)[187:org.openhab.binding.zwave:2.0.0.201609181624]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_91]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)[:1.8.0_91]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)[:1.8.0_91]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)[:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_91]

```

Full debug log is here.
[ise.txt](https://github.com/openhab/org.openhab.binding.zwave/files/482315/ise.txt)
##

**Comment by mhilbush** [comment]
Oddly, the log file I attached has a whole bunch of NULL characters at the beginning of the file.  Not sure where they came from...

I had done the following:
- from Karaf console bundle:stop the zwave binding
- delete my zwave log file
- from Karaf console bundle:start the zwave binding

**Comment by mhilbush** [comment]
Nothing new being added here, Chris.  Just adding a reference back to the more detailed analysis in the PR.

https://github.com/openhab/org.openhab.binding.zwave/pull/42#issuecomment-249442597

**Comment by mhilbush** [comment]
I'm going to close this as I believe the new transaction code had resolved the issue.
