### ISSUE TITLE
Exception during ZWave thread: Input 2. ArrayIndexOutOfBoundsException: 3

### ISSUE THREAD

**Issue by antares2001** [openhab/org.openhab.binding.zwave#433]
Hello @cdjackson,

here's a full report of the issue (which is not any more an NPE but an ArrayIndexOutOfBoundsException).

* OH2 Version: 
```
$ apt-cache policy openhab2
openhab2:
  Installed: 2.1.0~20170325134201-1
```

And the Stacktrace:
```
2017-03-28 15:31:31.863 [ItemStateChangedEvent     ] - zwave_device_a3edacb6_node6_switch_binary changed from NULL to OFF
2017-03-28 15:31:31.868 [ItemStateChangedEvent     ] - PLUG_UG_Basement changed from NULL to OFF
2017-03-28 15:31:42.574 [hingStatusInfoChangedEvent] - 'zwave:device:a3edacb6:node6' changed from ONLINE: Node initialising: DYNAMIC_VALUES to ONLINE: Node initialising: HEAL_START
2017-03-28 15:31:42.578 [hingStatusInfoChangedEvent] - 'zwave:device:a3edacb6:node6' changed from ONLINE: Node initialising: HEAL_START to ONLINE: Node initialising: DELETE_ROUTES
2017-03-28 15:31:42.899 [hingStatusInfoChangedEvent] - 'zwave:device:a3edacb6:node6' changed from ONLINE: Node initialising: DELETE_ROUTES to ONLINE: Node initialising: RETURN_ROUTES

==> /var/log/openhab2/openhab.log <==
2017-03-28 15:31:42.903 [ERROR] [ve.internal.protocol.ZWaveController] - Exception during ZWave thread: Input 2. {}
java.lang.ArrayIndexOutOfBoundsException: 3
	at org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveSecurityCommandClass.isSecurityNonceReportMessage(ZWaveSecurityCommandClass.java:1067)[183:org.openhab.binding.zwave:2.1.0.201702121957]
	at org.openhab.binding.zwave.internal.protocol.SerialMessage$SerialMessageComparator.compare(SerialMessage.java:692)[183:org.openhab.binding.zwave:2.1.0.201702121957]
	at org.openhab.binding.zwave.internal.protocol.SerialMessage$SerialMessageComparator.compare(SerialMessage.java:1)[183:org.openhab.binding.zwave:2.1.0.201702121957]
	at java.util.concurrent.PriorityBlockingQueue.siftUpUsingComparator(PriorityBlockingQueue.java:374)[:1.8.0_121]
	at java.util.concurrent.PriorityBlockingQueue.offer(PriorityBlockingQueue.java:491)[:1.8.0_121]
	at java.util.concurrent.PriorityBlockingQueue.add(PriorityBlockingQueue.java:463)[:1.8.0_121]
	at org.openhab.binding.zwave.internal.protocol.ZWaveController.enqueue(ZWaveController.java:546)[183:org.openhab.binding.zwave:2.1.0.201702121957]
	at org.openhab.binding.zwave.internal.protocol.initialization.ZWaveNodeInitStageAdvancer.sendMessage(ZWaveNodeInitStageAdvancer.java:260)[183:org.openhab.binding.zwave:2.1.0.201702121957]
	at org.openhab.binding.zwave.internal.protocol.initialization.ZWaveNodeInitStageAdvancer.addToQueue(ZWaveNodeInitStageAdvancer.java:1170)[183:org.openhab.binding.zwave:2.1.0.201702121957]
	at org.openhab.binding.zwave.internal.protocol.initialization.ZWaveNodeInitStageAdvancer.advanceNodeStage(ZWaveNodeInitStageAdvancer.java:1082)[183:org.openhab.binding.zwave:2.1.0.201702121957]
	at org.openhab.binding.zwave.internal.protocol.initialization.ZWaveNodeInitStageAdvancer.handleNodeQueue(ZWaveNodeInitStageAdvancer.java:230)[183:org.openhab.binding.zwave:2.1.0.201702121957]
	at org.openhab.binding.zwave.internal.protocol.initialization.ZWaveNodeInitStageAdvancer.ZWaveIncomingEvent(ZWaveNodeInitStageAdvancer.java:1306)[183:org.openhab.binding.zwave:2.1.0.201702121957]
	at org.openhab.binding.zwave.internal.protocol.ZWaveController.notifyEventListeners(ZWaveController.java:567)[183:org.openhab.binding.zwave:2.1.0.201702121957]
	at org.openhab.binding.zwave.internal.protocol.ZWaveController.handleIncomingRequestMessage(ZWaveController.java:250)[183:org.openhab.binding.zwave:2.1.0.201702121957]
	at org.openhab.binding.zwave.internal.protocol.ZWaveController.handleIncomingMessage(ZWaveController.java:214)[183:org.openhab.binding.zwave:2.1.0.201702121957]
	at org.openhab.binding.zwave.internal.protocol.ZWaveController.access$7(ZWaveController.java:208)[183:org.openhab.binding.zwave:2.1.0.201702121957]
	at org.openhab.binding.zwave.internal.protocol.ZWaveController$ZWaveInputThread.run(ZWaveController.java:1324)[183:org.openhab.binding.zwave:2.1.0.201702121957]
```

**Comment by cdjackson** [comment]
Probably caused by security key not being set or not correctly set looking at the error. As previously requested please revise a full debug log.

**Comment by antares2001** [comment]
Issue gone after reinstall.
